### ISSUE TITLE
How to add Orbit Controller to Norska?

### ISSUE THREAD

**Issue by ASoldo** [Plumie/Norska#13]
Hi, I've been playing with Norska today but I was not able to figure out how to make orbit controller. Are there any docs that I might have missed on how to add simple orbit controller so i can rotate around loaded meshes?

thank you!

**Comment by Plumie** [comment]
Hello,

Since orbitcontrols is a threejs addon that must be imported explicitly, there are a few things you can do to make it work with Norska.

You can attach it to an object like **window**, for example, and initialize it from the DOM.

### JS
```js
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';
// Attach it
window.OrbitControls = OrbitControls
```

### HTML
```html
<br x-effect="() => $three.controls = new window.OrbitControls($three.camera, $three.renderer.domElement)" />
```

It should work ! I will change the documentation to better explain how to do it.

**Comment by ASoldo** [comment]
Thank you! It works as you explained.
