### ISSUE TITLE
How to add lights?

### ISSUE THREAD

**Issue by ASoldo** [Plumie/Norska#15]
Hi, I'm exporting some simple scenes with Blender and when I don't include lights I cannot see that model/scene but if I export with lights then if I rotate the scene/model lights also move and I would like to have them stationary but only rotate model. So far I was not able to figure out how to add lights. Can you share how to do that?

Thank you!

**Comment by ASoldo** [comment]
I have exported lights separately and loaded them with `x-3.primitive` now I am able to load any `.glb` model and see it even if `.glb` doesn't have lights exported with it. Is this the solution?

**Comment by Plumie** [comment]
Hello, 

In Blender you don't need to use lights to see what your model looks like, but that's not the case with Three which is why it looks invisible when exported without lights (it's just very very dark).

If you want to see it without exporting the lights, you can place them manually in the scene, like an [ambient light](https://threejs.org/docs/?q=ambien#api/en/lights/AmbientLight) for example.

```html
<br x-3.ambientlight />
```

If you want the lights to be stationary but your model to rotate, I'm afraid you'll have to implement your own system yourself, because three's orbitcontrols addon only lets you rotate the camera around an object, and therefore the lights, but not the object itself. 
But that's more of a problem with Three than Norska 😔.

**Comment by ASoldo** [comment]
Can you please tell me how do we set options for lights?

This is how it looks when i export lights:
![image](https://github.com/Plumie/Norska/assets/1175537/633d8c89-31d8-44af-90dd-0ff13c61f2dc)

and this is how it looks now with markup below but i see this now:
![image](https://github.com/Plumie/Norska/assets/1175537/c21fcd22-173a-42ab-bc8b-3e403ed460cd)


```html
<br x-3.pointlight="0xFFFFFF, 1, 1000" x-3.$position.y="3" />
```
I'm guessing this is not correct... 👆

Can you show simple example for other types like sun and directional?

**Comment by ASoldo** [comment]
I figured this one out:
![image](https://github.com/Plumie/Norska/assets/1175537/743031f6-8000-419d-a360-ff4879a66e99)


```html
<br x-3.pointlight x-3.$color="0xFFFFFF" x-3.$intensity="100" x-3.$distance="1000" x-3.$decay="2" x-3.$position.y="3" />
```

**Comment by Plumie** [comment]
I think you can do something like that:

```html
<br x-3.pointlight="[0xFFFFFF, 100, 1000, 2]" x-3.$position.y="3" />
```
Constructor arguments are passed as an array like in the [documentation's example](https://docs.plume.moe/norska/core/objects), [or this codepen I made](https://codepen.io/plumiiie/pen/ZEZgXar) !
